training:
  loss:
    function: saq
    lambda_lc: 1.0
    lambda_lp: 0.2
    lambda_ent: 1.0
  optimizer:
    lr: 5.0e-4
    weight_decay: 5.0e-8
    min_lr: 1.0e-6
  schedule:
    epochs: 100
    test_batches: 200
    validation_batches: 20
    error_random_seed: 42
