# environment.yaml
name: syndrilla
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml
  - yamlordereddictloader
  - pyfiglet
  - loguru
  - pip
  - numpy
  - scipy
  - nvidia-ml-py
  - pytorch=2.13.0=cuda130*
  - matplotlib
  - ninja
  - pytest
  - libstdcxx-ng>=14
  - cuda-version=13.0
  - cuda-nvcc=13.0
  - cuda-cudart-dev=13.0
  - libcublas-dev
  - libcusparse-dev
  - libcusolver-dev
  - pip:
    - ldpc
    - stim  # conda-forge 'stim' is an unrelated package
