decoder:
  algorithm: saq
  check_type: hx
  dtype: float32
  device:
    device_type: cpu
    device_idx: 0
  config:
    model:
      d_model: 128
      N_dec: 4
      h: 8
      dropout: 0.0
      no_mask: 0
    cpnd:
      enable: true
      passes: 1
    optimizer:
      lr: 5.0e-4
      weight_decay: 5.0e-8
      min_lr: 1.0e-6
    train:
      epochs: 40
      test_batches: 100
      validation_batches: 20
      error_random_seed: 42
